### ISSUE TITLE
Cannot uninstall or install plugins

### ISSUE THREAD

**Issue by humac** [mkellsy/homebridge-config-ui#18]
When trying to uninstall a plugin I get the following error:

Error message: 
fs is not defined
Details:
ReferenceError: fs is not defined
    at /usr/lib/node_modules/homebridge-config-ui/routes/plugins.js:94:5
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at /usr/lib/node_modules/homebridge-config-ui/routes/plugins.js:51:9
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:317:13)
    at /usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at /usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:635:15
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:47:12)

I get the following error when trying to install:

Error message: 
Unexpected token u in JSON at position 0
Details:
SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at /usr/lib/node_modules/homebridge-config-ui/routes/plugins.js:138:29
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at /usr/lib/node_modules/homebridge-config-ui/routes/plugins.js:129:9
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:317:13)
    at /usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at /usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:635:15
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)

For the install I provided the following data in the platform section after searching for and selecting install on the desired plugin:
Name field: Homebridge Info

Other field: {
    "platform": "Info",
    "npm_package": "homebridge-info"
}

**Comment by shidevil** [comment]
Uninstall is working after adding at the top of routes/plugin.js

var fs = require("fs"); 

For installing, i am still debugging it. Encountered the same issue as well.

**Comment by humac** [comment]
@shidevil ok I will give the uninstall fix a try.

**Comment by humac** [comment]
@shidevil when I try to delete it no longer errors and when I look at the logs I see the following entry:

Aug 17 15:14:43 raspberrypi homebridge[2262]: [8/17/2017, 3:14:43 PM] [Config] Package homebridge-server removed.

However when I go look at the node_modules folder I still see the homebridge-server plugin that I am trying to delete.

**Comment by shidevil** [comment]
@humac that is weird let me check as mine successfully uninstalled.

**Comment by shidevil** [comment]
@humac i was unable to replicate the issue. You need to restart homebridge after editing the files. Could you try again?

**Comment by shidevil** [comment]
@humac could you check the fix. Check plugin.js on the pull request to edit it and test it out.

**Comment by humac** [comment]
@shidevil ok i'll give it a try later today and report back thanks

**Comment by shidevil** [comment]
@humac Please note that if you were to install an accessories. The platform need to be remove. Including the bracket. Just to take note. 

<img width="930" alt="screen shot 2017-08-19 at 3 35 15 am" src="https://user-images.githubusercontent.com/5009021/29488665-4b0a2174-8542-11e7-84bc-3eea65e1ecf2.png">

**Comment by humac** [comment]
@shidevil sorry I haven't had time to try this yet. But was wondering if any changes were made to the main repo and if is did an npm upgrade of homebridge-config-ui will these changes be brought in or do I have to manually make the update myself?

**Comment by shidevil** [comment]
@humac it isn't updated on this repo as the pull request is not merged. So can't do a npm upgrade. Sorry

**Comment by humac** [comment]
@shidevil ok thanks i'll manually make the update then

**Comment by shidevil** [comment]
@humac

sudo npm -g uninstall homebridge-config-ui

Download/clone my fork. 
cd into the folder of my fork u clone/downloaded
sudo npm -g install

**Comment by humac** [comment]
@shidevil I was just thinking of doing that thanks

**Comment by humac** [comment]
@shidevil I cloned and installed your fork and I see it added a temp display to the UI so I know I'm running your latest.  That said when I go to uninstall a plugin it still does not uninstall.  When I tail the logs I see:

Aug 29 03:11:10 raspberrypi homebridge[6329]: [8/29/2017, 3:11:10 AM] [Config] Package homebridge-server removed.

But when I go to /usr/lib/node_modules I still see the homebridge-server plugin

This is also the same result when I try to install a plugin

Aug 29 03:16:11 raspberrypi homebridge[6329]: [8/29/2017, 3:16:11 AM] [Config] Package homebridge-camera-ffmpeg-omx installed.

But nothing new in /usr/lib/node_modules

Huy

**Comment by humac** [comment]
@shidevil it did however add a platform to the config.json file

**Comment by shidevil** [comment]
@humac okay will check on it. since it's installed in /usr/lib/node_module. mine was in usr/local/lib.

Will look into it. thank you for testing.

**Comment by shidevil** [comment]
@humac sorry i just checked on my other setup. it is at usr/lib/node_modules. Interesting.. 

Did you give homebridge service root access?? i just tried on my side to install homebridge-camera-ffmpeg-omx it appears on my homebridge UI

<img width="684" alt="screen shot 2017-08-30 at 12 16 12 am" src="https://user-images.githubusercontent.com/5009021/29831689-81377e6c-8d18-11e7-9ae3-66f419a3b587.png">
<img width="940" alt="screen shot 2017-08-30 at 12 16 19 am" src="https://user-images.githubusercontent.com/5009021/29831690-813c3100-8d18-11e7-8963-e2aef67dd31c.png">
<img width="694" alt="screen shot 2017-08-30 at 12 15 28 am" src="https://user-images.githubusercontent.com/5009021/29831688-81305eb6-8d18-11e7-9411-c73e66a15fbf.png">

**Comment by shidevil** [comment]
@humac i just tested if i were to run homebridge without root access, it will not work. If you did not give homebridge root access. Install/uninstall will not work.

So that being said. You can do a simple test.

Make sure that /root/.homebridge/config.json has the configuration as per /var/homebridge or /home/pi/.homebridge/config.json

do a sudo homebridge and try again.

**Comment by humac** [comment]
I have homebridge running under pi with the config sitting under /var/lib/homebridge.  pi user has sudo access so should this not be enough?

**Comment by shidevil** [comment]
pi user has sudo access? Let me check. As I'm running my homebridge via root user and not pi user with sudo access.

**Comment by humac** [comment]
@shidevil yes pi user has sudo.   So I did your test and it worked, copied the config over to root user and ran sudo homebridge and it worked.  I'd prefer not to run things as root though

**Comment by shidevil** [comment]
Does ur sudo require password on pi user? I will check on this.

**Comment by humac** [comment]
nope

**Comment by humac** [comment]
I switched to running homebridge to root user for now so I can use the UI to manage homebridge when I don't have access to the cli.

**Comment by shidevil** [comment]
@humac could you help me to check something?

sudo nano /etc/systemd/system/homebridge.service

could you tell me which user did you put there? thank you

**Comment by r32er** [comment]
Hey guys. I installed your plugin and the install of plugin result in the same error as @humac. 

My Homebridge run as systemd. I’ve only tried to install a plugin, no uninstall yet.

**Comment by mkellsy** [comment]
Homebridge relies on global Node deps. Since the npm install -g needs to run as su, the processes that homebridge is running in might not have access to install. Either loosen your SELinux rules or run homebridge as root.

**Comment by mkellsy** [comment]
This work is continued in this project [Homebridge(X)](https://github.com/mkellsy/homebridge-x).
