### ISSUE TITLE
Cannot access Configuration

### ISSUE THREAD

**Issue by SWEiNSANE** [mkellsy/homebridge-config-ui#19]
Hi,

First of all I just want to say that I really like your application.

I cannot access Configuration since this error message appears:
_TypeError: Cannot read property 'length' of undefined
    at write (/usr/lib/node_modules/homebridge-config-ui/routes/config.js:115:43)
    at /usr/lib/node_modules/homebridge-config-ui/routes/config.js:13:5
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at /usr/lib/node_modules/homebridge-config-ui/routes/config.js:7:9
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:317:13)_

Perhaps an permission error? I can't access the /var/log/daemon.log since I'm not logging until I ran 
sudo chmod -R 0777 /var/log/daemon.log - should even that be necessary?! My user pi isn't part of the adm group I believe?!

**Comment by shidevil** [comment]
Please post ur config.json

**Comment by SWEiNSANE** [comment]
I replaced tokens and keys with another texts:
{
	"bridge": {
		"name": "HomebridgeHumlegatan",
		"username": "aa:bb:bb:dd:ee:ff",
		"port": 12345,
		"pin": "111-11-11"
	},
	"description": "Telldus plugin",
	"platforms": [{
		"platform": "Telldus",
		"name": "Telldus Liv!e",
		"public_key": "PUBLIC_KEY",
		"private_key": "PRIVATE_KEY",
		"token": "TOKEN",
		"token_secret": "TOKEN_SECRET"
	}, {
		"platform": "Ikea",
		"name": "Gateway",
		"ip": "192.168.1.1",
		"psk": "psk"
	},
	{
    		"platform": "config",
    		"name": "Config",
    		"port": 8080,
    		"log": "/var/log/daemon.log",
    		"restart": "sudo systemctl restart homebridge"
	}]
}

**Comment by shidevil** [comment]
Try this instead

```
{
"bridge": {
"name": "HomebridgeHumlegatan",
"username": "aa:bb:bb:dd:ee:ff",
"port": 12345,
"pin": "111-11-11"
},
"description": "Telldus plugin",
"platforms": [{
"platform": "Telldus",
"name": "Telldus Liv!e",
"public_key": "PUBLIC_KEY",
"private_key": "PRIVATE_KEY",
"token": "TOKEN",
"token_secret": "TOKEN_SECRET"
}, {
"platform": "Ikea",
"name": "Gateway",
"ip": "192.168.1.1",
"psk": "psk"
},
{
"platform": "config",
"name": "Config",
"port": 8080,
"log": "/var/log/daemon.log",
"restart": "sudo systemctl restart homebridge"
}],
"accessories":[]
}
```

**Comment by SWEiNSANE** [comment]
Adding "accessories":[] did the trick - thanks for your swift support!

**Comment by shidevil** [comment]
@SWEiNSANE Welcome!
