### ISSUE TITLE
Status screen should not require an internet connection

### ISSUE THREAD

**Issue by drfahod** [mkellsy/homebridge-config-ui#28]
Homebridge break with error when no internet

`
TypeError: Cannot read property 'collected' of undefined
    at Request._callback (/usr/local/lib/node_modules/homebridge-config-ui/npm.js:135:41)
    at self.callback (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/request/request.js:188:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/request/request.js:884:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
`

**Comment by mkellsy** [comment]
The status screen checks the Homebridge NPM package for updates.
