### ISSUE TITLE
Search plugin causes termination of homebridge server

### ISSUE THREAD

**Issue by Herbert-Hotz** [mkellsy/homebridge-config-ui#34]
When i select URL http://192.168.1.100:8080/plugins, the following error is reported and the server dies:

```
/root/.nvm/versions/node/v8.9.0/lib/node_modules/homebridge-config-ui/npm.js:97
                    for (var i = 0; i < body.results.length; i++) {
                                                     ^

TypeError: Cannot read property 'length' of undefined
    at Request._callback (/root/.nvm/versions/node/v8.9.0/lib/node_modules/homebridge-config-ui/npm.js:97:54)
    at Request.self.callback (/root/.nvm/versions/node/v8.9.0/lib/node_modules/homebridge-config-ui/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/.nvm/versions/node/v8.9.0/lib/node_modules/homebridge-config-ui/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/.nvm/versions/node/v8.9.0/lib/node_modules/homebridge-config-ui/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

[1]+  Exit 1                  homebridge
```

**Note:**
My solution to overcome the several issues with this plugin was:
`npm uninstall homebridge-config-ui -g --unsafe-perm`
`npm install homebridge-config-ui-x -g --unsafe-perm`
(_config.json_ remains the same)

**Comment by cerniuk** [comment]
homebridge-config-ui-x plugin works nicely with one small issue, it downloads the HTML for NPM pages, but overall nice and nicely thought out.

**Comment by mkellsy** [comment]
I agree. I never liked how this was setup. I am going to pick this project back up, have had a lot going on lately, sorry. I want to separate the UI from the Homebridge service. A stack so to say. I do like what oznu as done with homebridge-config-ui-x, they added the control which was my next step.

**Comment by mkellsy** [comment]
Fixed in HOOBS 3
