### ISSUE TITLE
won't start. getting error

### ISSUE THREAD

**Issue by RedSquid06** [mkellsy/homebridge-config-ui#36]
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[5/12/2018, 3:19:27 PM] [Config] Console is listening on port 33756.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1271:14)
    at listen (net.js:1307:10)
    at Server.listen (net.js:1403:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:126:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:96:10)

this is my config:

        "platforms": [{
                "platform": "config",
                "name": "Config",
                "port": 33756,
                "log": "/var/log/homebridge.stdout.log",
                "error_log": "/var/log/homebridge.stderr.log",
                "restart": "/usr/local/bin/supervisorctl restart homebridge"
        }]

**Comment by mkellsy** [comment]
This is an issue with homebridge or hap-nodejs. Please refer to their projects, we can not do anything here. Sorry.
