### ISSUE TITLE
Can't save changes in config

### ISSUE THREAD

**Issue by Krocko** [mkellsy/homebridge-config-ui#6]
Get the following error after editing the config and trying to save 

TypeError: Cannot read property 'length' of undefined

**Comment by mkellsy** [comment]
Can you include the entire stack trace?

**Comment by Krocko** [comment]
Here it is.
```
TypeError: Cannot read property 'length' of undefined
    at save (/usr/local/lib/node_modules/homebridge-config-ui/routes/config.js:149:42)
    at /usr/local/lib/node_modules/homebridge-config-ui/routes/config.js:24:5
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at /usr/local/lib/node_modules/homebridge-config-ui/routes/config.js:18:9
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:635:15
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
```

Also if i edit the Port or the HomeKit pin, nothing happened if i press the save button.

**Comment by Nastra888** [comment]
For me is the same error.

**Comment by mkellsy** [comment]
It looks like this is happening when you have only 1 platform or accessory. I have this fixed in version 1.1.3

**Comment by Krocko** [comment]
After i try to edit the config my config.json looks like this
```
{
    "bridge": {
        "port": 51826
    },
    "accessories": [],
    "platforms": []
}
```

Also i have no more write access to the config.json

In the Config Tap, i can´t save my changes. If i add an accessory ore an platform and reload the page, nothing is added.

**Comment by mkellsy** [comment]
1.1.3 released.

**Comment by Krocko** [comment]
Any idea to fix this bug?

**Comment by mkellsy** [comment]
It is fixed in version 1.1.3 or higher.

**Comment by Krocko** [comment]
I have installed version 1.1.4

If i try to edit something on the following Page and hit the save button, nothing happened and the changes don´t save.
>>![bildschirmfoto 2017-07-26 um 17 38 31](https://user-images.githubusercontent.com/29394115/28630883-cc3d4e12-722b-11e7-86ca-ef48a767de3a.png)


When i use the advanced editor.
>>![ohne titel](https://user-images.githubusercontent.com/29394115/28630998-1ec5eb26-722c-11e7-84b6-5ac6881939b7.jpeg)



If i change something now, my original config.json is renamed to "config.json.1501084111"
>>![ohne titel2](https://user-images.githubusercontent.com/29394115/28631195-b44d658e-722c-11e7-8a09-e3aa63a29433.jpeg)



And the new config.json is looking so.
>>![ohne titel1](https://user-images.githubusercontent.com/29394115/28631236-d4a80bfe-722c-11e7-8b22-f5e66e59b71f.jpeg)




I hope you can understand.

**Comment by Krocko** [comment]
Any news about this?
Or anybody else with this problem?

**Comment by mkellsy** [comment]
I will look into this. I was able to recreate the condition. I think there might be something else happening here.

**Comment by shidevil** [comment]
I wasn't able to recreate the condition except that if i save the file(not the advanced editor), the old config file is renamed into config.1502360780

my file was saved successfully running raspbian using systemd.

**Comment by shidevil** [comment]
@Krocko 

I have pull request for this fixed. You can check it out as well. It's just editing one line 

Go to the node_modules folder, find the homebridge-config-ui, open the views folder.

Edit advanced.html and look for 

> <form id="advanced-config" action="/config" method="post">

change /config to /config/advanced

> <form id="advanced-config" action="/config/advanced" method="post">

**Comment by Krocko** [comment]
This worked for the advanced editor. Thank you.
Any solution, to get the save button to work in the guided editor?

**Comment by shidevil** [comment]
@Krocko 

More details please?

As my guided editor is working fine as well. What did you do to create an error?

**Comment by Krocko** [comment]
https://user-images.githubusercontent.com/29394115/28630883-cc3d4e12-722b-11e7-86ca-ef48a767de3a.png

If i change something on this screen and hit the save button, the changes are not accepted.

**Comment by shidevil** [comment]
Ok let me try.

**Comment by shidevil** [comment]
@Krocko I just tried again. it's working. 

I changed port, pin, mac address, accessories and platform. 

All works fine on guided editor

**Comment by Krocko** [comment]
Have you reload the page, to look if the changes stick?

**Comment by shidevil** [comment]
Yes changes stick, in my /var/homebridge/config.json files as well.

**Comment by Krocko** [comment]
Strange. Have installed your fork. Now i got the following error:
```
ReferenceError: now is not defined
    at /usr/local/lib/node_modules/homebridge-config-ui/routes/config.js:56:50
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at /usr/local/lib/node_modules/homebridge-config-ui/routes/config.js:48:9
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:635:15
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/usr/local/lib/node_modules/homebridge-config-ui/node_modules/passport/lib/middleware/authenticate.js:325:9) 
```

**Comment by shidevil** [comment]
@Krocko go to route/config.js

There's an extra + symbol. remove it

**Comment by Krocko** [comment]
Don´t understand. In wich line i have to remove the + symbol?

**Comment by shidevil** [comment]
line 56.

**Comment by shidevil** [comment]
check my latest commit. Thanks

**Comment by Krocko** [comment]
Ok. Thanks. Will use advanced editor for now.

**Comment by shidevil** [comment]
@Krocko Still can't get guided editor to work? 

Can i know your homebridge system running on? Node version, Npm version, what accessories and platforms. Could you upload your config.json here?

as i tried multiple cases on mine, guided works fine perfectly. So it's best if you could check on ur end as well.

**Comment by Krocko** [comment]
Homebridge --> systemd 
Node --> 8.1.2
Npm --> 5.3.0

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 42837,
        "pin": "031-45-154"
    },
    "accessories": [
        {
            "accessory": "PiTemperature",
            "name": "Raspberry PI Temperatur"
        },
        {
            "accessory": "Suncalc",
            "location": {
                "lat": 50.9787,
                "lng": 11.03283
            },
            "offset": {
                "sunriseEnd": 30,
                "sunsetStart": -30
            },
            "name": "Tageszeitraum"
        },
        {
            "accessory": "DelaySwitch",
            "name": "Zeitschalter 45 Min",
            "delay": 2400000
        },
        {
            "accessory": "SonoffTasmotaHTTP",
            "name": "Spiegel",
            "hostname": "192.168.2.50"
        },
        {
            "accessory": "DummySwitch",
            "name": "Fakeschalter"
        },
        {
            "accessory": "CmdTrigger",
            "name": "Backup Homebridge",
            "command": "/home/pi/Documents/Dropbox-Uploader/dropbox_uploader.sh upload /var/homebridge /Dokumente/Sicherungen/Homebridge/Backup_$(date +%d.%m.%Y-%H:%M)"
        },
        {
            "accessory": "CmdTrigger",
            "name": "Neustart Homebridge",
            "command": "sudo systemctl restart homebridge"
        },
        {
            "accessory": "CmdTrigger",
            "name": "Neustart Raspi",
            "command": "sudo reboot"
        },
        {
            "accessory": "AveaBulb",
            "name": "Avea Bulb"
        }
    ],
    "platforms": [
        {
            "name": "Harmony Hub Wohnzimmer",
            "platform": "HarmonyHub"
        },
        {
            "platform": "eveatmo",
            "name": "Eveatmo",
            "ttl": 10,
            "auth": {
                "client_id": "xxxx",
                "client_secret": "xxxx",
                "username": "xxxx",
                "password": "xxxx"
            }
        },
        {
            "platform": "Hue",
            "name": "Philips Hue",
            "host": "192.168.2.40",
            "users": {
                "Xxx": "xxx"
            },
            "sensors": true,
            "excludeSensorTypes": [
                "Daylight",
                "CLIP",
                "Geofence"
            ],
            "lights": true,
            "philipsLights": true
        },
        {
            "platform": "Fritz!Box",
            "name": "FRITZ!Box",
            "username": "xxx",
            "password": "xxx",
            "url": "http://192.168.2.1",
            "interval": 60,
            "options": {
                "strictSSL": false
            }
        },
        {
            "platform": "People",
            "name": "Anwesenheitserkennung",
            "threshold": 10,
            "anyoneSensor": true,
            "nooneSensor": true,
            "webhookPort": 51828,
            "pingInterval": 10000,
            "ignoreReEnterExitSeconds": 0,
            "people": [
                {
                    "name": "x",
                    "target": "192.168.2.33"
                },
                {
                    "name": "xx",
                    "target": "192.168.2.41",
                    "ignoreReEnterExitSeconds": 300
                },
                {
                    "name": "xxx",
                    "target": "192.168.2.61"
                }
            ]
        },
        {
            "platform": "Nest",
            "name": "Rauchmelder",
            "token": "xxx",
            "clientId": "xxx",
            "clientSecret": "xxx",
            "code": "xxx",
            "username": "xxx",
            "password": "xxx"
        },
        {
            "platform": "AmazonDash",
            "name": "Amazon Dash Buttons",
            "buttons": [
                {
                    "name": "Play Doh",
                    "mac": "B4:7C:9C:9D:23:3C"
                },
                {
                    "name": "Power Point",
                    "mac": "AC:63:BE:65:B1:CA"
                },
                {
                    "name": "Scott",
                    "mac": "FC:A6:67:1B:0F:B2"
                },
                {
                    "name": "Playboy",
                    "mac": "B4:7C:9C:73:40:F5"
                }
            ]
        },
        {
            "platform": "DysonPlatform",
            "name": "Dyson Link",
            "accessories": [
                {
                    "ip": "192.168.2.51",
                    "displayName": "Dyson Pure Cool Link",
                    "serialNumber": "xxx",
                    "password": "xxx"
                }
            ]
        },
        {
            "platform": "config",
            "name": "Homebridge Konfiguration",
            "port": 8765,
            "log": "/var/log/daemon.log",
            "error_log": "/var/log/syslog",
            "restart": "sudo systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp"
        }
    ]
}
```

**Comment by shidevil** [comment]
@Krocko still unable to replicate this for guided editor as i do not have so many accessories or platform. I could create fake platforms and accessories but it would not be a ideal test setup. Could you do a debug log when u try to use the guided editor and save?

**Comment by Krocko** [comment]
Will do it after vacation.

**Comment by humac** [comment]
I'm not sure if this is the same issue but I get an error if I simply try to access the config page.  I don't see anything but the error message.

TypeError: Cannot read property 'length' of undefined
    at write (/usr/lib/node_modules/homebridge-config-ui/routes/config.js:115:43)
    at /usr/lib/node_modules/homebridge-config-ui/routes/config.js:13:5
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at /usr/lib/node_modules/homebridge-config-ui/routes/config.js:7:9
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:317:13)
    at /usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:275:10)
    at /usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:635:15
    at next (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/lib/node_modules/homebridge-config-ui/node_modules/express/lib/router/index.js:174:3)

**Comment by shidevil** [comment]
@humac could you show your config file? Thanks

**Comment by humac** [comment]
@shidevil 
Here is my config file:

{
    "bridge": {
        "name": "Homebridge",
        "username": "XXXX",
        "port": XXXX,
        "pin": "031-45-154"
    },
    "platforms": [
        {
            "platform": "config",
            "port": XXXX,
            "name": "Config",
            "log": "/var/log/daemon.log",
            "error_log": "/var/log/syslog",
            "restart": "sudo service homebridge restart"
        },
        {
            "platform": "netatmo",
            "name": "netatmo weather",
            "ttl": 5,
            "auth": {
                "client_id": "XXXX",
                "client_secret": "XXXX",
                "username": "huyXXXX",
                "password": "XXXX"
            }
        },
        {
            "platform": "homebridge-smartthings.SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "XXXX",
            "access_token": "XXXX",
            "polling_seconds": 3600,
            "update_method": "direct",
            "direct_ip": "XXXX",
            "direct_port": XXXX
        },
        {
            "platform": "Nest",
            "name": "Nest",
            "token": "XXXX",
            "clientId": "XXXX",
            "clientSecret": "XXXX",
            "code": "XXXX",
            "username": "huyXXXX",
            "password": "XXXX"
        }
    ]
}

**Comment by shidevil** [comment]
@humac 

Try this config

{
"bridge": {
"name": "Homebridge",
"username": "XXXX",
"port": XXXX,
"pin": "031-45-154"
},
"platforms": [
{
"platform": "config",
"port": XXXX,
"name": "Config",
"log": "/var/log/daemon.log",
"error_log": "/var/log/syslog",
"restart": "sudo service homebridge restart"
},
{
"platform": "netatmo",
"name": "netatmo weather",
"ttl": 5,
"auth": {
"client_id": "XXXX",
"client_secret": "XXXX",
"username": "huyXXXX",
"password": "XXXX"
}
},
{
"platform": "homebridge-smartthings.SmartThings",
"name": "SmartThings",
"app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
"app_id": "XXXX",
"access_token": "XXXX",
"polling_seconds": 3600,
"update_method": "direct",
"direct_ip": "XXXX",
"direct_port": XXXX
},
{
"platform": "Nest",
"name": "Nest",
"token": "XXXX",
"clientId": "XXXX",
"clientSecret": "XXXX",
"code": "XXXX",
"username": "huyXXXX",
"password": "XXXX"
}
],
"accessories":[]
}

**Comment by humac** [comment]
@shidevil That worked thanks.

**Comment by shidevil** [comment]
@humac welcome :)

**Comment by Krocko** [comment]
@shidevil I looked in the debug log an there is no entry, if I hit the save button.

**Comment by shidevil** [comment]
@Krocko I'm using chrome :)

**Comment by Krocko** [comment]
Ok. Have testet this with Safari and chrome. It is the same with both browsers. Nothing happened in the log, if I press the save button.

**Comment by shidevil** [comment]
@Krocko Did you enable debug=*? What node version are u using?

**Comment by Krocko** [comment]
Yes of course

**Comment by shidevil** [comment]
@Krocko without any logs i couldn't be able to replicate either. Should have some logs if you run debug=*

**Comment by Krocko** [comment]
I don't want to post this logs in public. Any chance to send you the logs privat? Are you on slack?

**Comment by shidevil** [comment]
@Krocko 

yes i'm on slack. It's the same user(shidevil)

**Comment by Krocko** [comment]
Can't find you.

**Comment by shidevil** [comment]
https://homebridgeconfigui.slack.com/

**Comment by Krocko** [comment]
Can't join this team 😩

**Comment by shidevil** [comment]
@Krocko https://join.slack.com/t/homebridgeconfigui/shared_invite/MjI4ODU3NjU1NzE3LTE1MDMwODIxNDQtNDU3MjdlYjk0NA

**Comment by dehsgr** [comment]
I've the same thing here too on one homebridge instance. One works, one not. The one, where saving doesn't work there are no things in log, regardless, which browsers are used.

- System is running on pi3
- node v6.11.4
- npm v3.10.10
- homebridge is running via systemd as root user

**Comment by dehsgr** [comment]
Ah! I found sth! ;-)

If there is an "!" within name or platform name on config page, save will not work. Browser console is reporting the following:

`Error: Syntax error, unrecognized expression: #Fritz!Box-code  jquery.min.js:2:13370`

**Comment by shidevil** [comment]
@dehsgr are u using the original master? or the pull request i made?

**Comment by dehsgr** [comment]
@shidevil I use pull request on both bridges, because of e.g. the issue with login (#15, yesterday closed).

**Comment by shidevil** [comment]
@dehsgr thats interesting. So in your config page u put a "!" and save will not work? 

also on another homebridge instance, one works while one does not work.

Could i check if the one that does not work, is there any error log? thank you

**Comment by dehsgr** [comment]
@shidevil the difference is that one bridge is using plugin https://www.npmjs.com/package/homebridge-fritz (which assumes "!" in its config). The other one doesn't. There is no specific log entry in homebridge itself. only the entry I gave you from browser console.

**Comment by shidevil** [comment]
@dehsgr so there’s only one instance with problem am I right? 

Are both instances the same npm and node version? 

Save that normally does not work may be due to systemd. Could you try running manually? sudo homebridge -D 

See if save works. Make sure to edit the config.json at ~/.homebridge/

**Comment by dehsgr** [comment]
@shidevli yes, only one instance is affected. It‘s the one with „!“ in JSON. Doesn‘t have to do with systemd.

**Comment by shidevil** [comment]
@dehsgr i think i understood your problem. Let me see if i can allow expression of "!" in the code. Will review during the weekend

**Comment by shidevil** [comment]
@dehsgr could you make a new issue for this. Thanks

**Comment by dehsgr** [comment]
@shidevil it's done (issue #27).
